/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 bluewhale.gltf --transform
Author: Bohdan Lvov (https://sketchfab.com/ostapblendercg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-whale-textured-d24d19021c724c3a9134eebcb76b0e0f
Title: Blue Whale - Textured
*/

import React                      from 'react'
import { useGLTF }                from '@react-three/drei'
import { useConvexPolyhedron }    from '@react-three/cannon';

export function BlueWhaleModel(props) {
  const { nodes, materials } = useGLTF('/bluewhale-transformed.glb')
  const [ref] = useConvexPolyhedron(() => ({ mass: 0, position: [0, 5, 0], ...props}));
  return (
    <group ref={ref} {...props} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={286.42}>
          <group name="WhaleAnim03fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="locator3" position={[0, 0.34, 0.67]} rotation={[0.04, 0, 0]}>
                  <group name="Object_7">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.lambert1} skeleton={nodes.Object_37.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bluewhale-transformed.glb')