/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 ghostkeel.gltf --transform
Author: Apothecary.Kekoulis (https://sketchfab.com/apothecarykekoulis)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/xv95-ghostkeel-battlesuit-216dfa3d736d4784977ead776917f312
Title: XV95 Ghostkeel Battlesuit
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function GhostKeelModel(props) {
  const { nodes, materials } = useGLTF('/ghostkeel-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-4.5, -8.47, 8.48]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_1'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-12.9, -1.46, 1.3]} rotation={[-1.63, 0.17, -1.8]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_2'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-15.77, -4.56, -14.3]} rotation={[-1.44, 0.24, -1.8]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_3'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[0.47, -3.36, -2.81]} rotation={[-1.57, 0.02, -1.48]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_4'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[0.3, 101.18, 4.07]} rotation={[-Math.PI / 2, 0, -1.54]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_5'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[0.99, -3.35, -3.09]} rotation={[-1.57, 0.02, -1.48]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_6'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[2.08, -2.94, -20.89]} rotation={[-1.37, 0, -1.48]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_7'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[8.94, 9.23, -38.14]} rotation={[-0.95, -0.09, -1.63]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_8'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[2.08, -2.94, -20.89]} rotation={[-1.37, 0, -1.48]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_9'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[2.08, -2.94, -20.89]} rotation={[-1.37, 0, -1.48]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_10'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[2.08, -2.94, -20.89]} rotation={[-1.37, 0, -1.48]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_11'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[1.91, -3.33, -2.81]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_12'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-11.37, 16.07, 49.77]} rotation={[-2.21, 0.12, -1.68]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_13'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-11.37, 16.07, 49.77]} rotation={[-2.21, 0.12, -1.68]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_14'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-11.37, 16.07, 49.77]} rotation={[-2.21, 0.12, -1.68]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_15'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-11.37, 16.07, 49.77]} rotation={[-2.21, 0.12, -1.68]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_16'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-11.37, 16.07, 49.77]} rotation={[-2.21, 0.12, -1.68]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_17'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-60.55, -4.77, -13.51]} rotation={[-1.44, 0.24, -1.8]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_18'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-57.68, -1.68, 2.09]} rotation={[-1.63, 0.17, -1.8]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_19'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[-49.28, -8.68, 9.27]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_20'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[2.6, -3.33, -3.02]} rotation={[-Math.PI / 2, 0, -1.48]} scale={15.5} />
          <mesh geometry={nodes['FBXASC0481FBXASC032-FBXASC032Default_21'].geometry} material={materials['FBXASC0481FBXASC032-FBXASC032Default']} position={[2.89, -2.93, -3.02]} rotation={[-Math.PI / 2, 0, -1.48]} scale={15.5} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ghostkeel-transformed.glb')
