/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 stormsurge.gltf --transform
Author: Frag_Jacker (https://sketchfab.com/Frag_Jacker)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tau-kv128-stormsurge-37ab137d8cb849949dc3221721e5ac9f
Title: Tau KV128 Stormsurge
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function StormSurgeModel(props) {
  const { nodes, materials } = useGLTF('/stormsurge-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_8.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_9.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_10.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_11.geometry} material={materials.Legs} />
          <mesh geometry={nodes.defaultMaterial_12.geometry} material={materials.railgun} />
          <mesh geometry={nodes.defaultMaterial_13.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_14.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_15.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_16.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_17.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_18.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_19.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_20.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_21.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_22.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_23.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_24.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_25.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_26.geometry} material={materials.torso} />
          <mesh geometry={nodes.defaultMaterial_27.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_28.geometry} material={materials.hips_and_heads} />
          <mesh geometry={nodes.defaultMaterial_29.geometry} material={materials.weapons} />
          <mesh geometry={nodes.defaultMaterial_30.geometry} material={materials.hips_and_heads} />
          <mesh geometry={nodes.defaultMaterial_31.geometry} material={materials.hips_and_heads} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/stormsurge-transformed.glb')
